#%RAML 1.0
title: plm_esb
baseUri: 0.0.0.0:4001
description: ESB API For PLM
version: 1.0
mediaType: application/json

/getAgvInfo:
  get:
    responses:
      '200':
        body:
          application/json:
/commandOrder:
  post:
    body:
      application/json:
        example: '{"destinationAction":"NONE","destinationId":2,"id":10,"orderId":1}'

    responses:
      '200':
        body:
          application/json:
/setAvgInfo:
  post:
    body:
      application/json:
        example: |
          {
            "currOrderId": 0,
            "energyLevel": 100,
            "lastFinishedOrderId": 0,
            "lastReceivedOrderId": 0,
            "loadState": "EMPTY",
            "operatingState": "IDLE",
            "positionId": 1,
            "telegramCounter": 0
          }

    responses:
      '200':
        body:
          application/json: