#%RAML 1.0
title: plm_esb
baseUri: 0.0.0.0:4001
description: ESB API For PLM
version: 1.0
mediaType: application/json

/getAgvInfo:
  get:
    responses:
      '200':
        body:
          application/json:
/commandOrder:
  post:
    body:
      application/json:
    responses:
      '200':
        body:
          application/json:
